name: build
on:
  push:
    branches: 
      - "**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest

    steps:
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23.8

    - uses: extractions/setup-just@v1
      with:
        just-version: '1.40.0'

    - name: Install libpcap-dev (Linux)
      if: "matrix.os == 'ubuntu-latest'"
      run: sudo apt-get update && sudo apt-get install -y libpcap-dev

    - name: Install Npcap SDK (Windows)
      if: "matrix.os == 'windows-latest'"
      run: |
        Invoke-WebRequest -Uri "https://npcap.com/dist/npcap-sdk-1.15.zip" -OutFile "npcap-sdk.zip"
        Expand-Archive -Path "npcap-sdk.zip" -DestinationPath "C:\"
        $dir = Get-ChildItem -Path "C:\" -Directory | Where-Object { $_.Name -like "npcap-sdk*" } | Select-Object -First 1
        Rename-Item -Path $dir.FullName -NewName "wpdpack"
      shell: powershell

    - name: Set CGO flags for Npcap (Windows)
      if: "matrix.os == 'windows-latest'"
      run: |
        echo "CGO_CFLAGS=-IC:\wpdpack\Include" >> $env:GITHUB_ENV
        echo "CGO_LDFLAGS=-LC:\wpdpack\Lib" >> $env:GITHUB_ENV
      shell: powershell

    - name: checkout
      uses: actions/checkout@v4

    - name: build
      run: just build test

    - name: Convert coverage format to lcov
      if: "matrix.os == 'ubuntu-latest'"
      uses: jandelgado/gcov2lcov-action@v1.0.0
      with:
        infile: coverage.out
        outfile: coverage.lcov

    - name: coveralls
      if: "matrix.os == 'ubuntu-latest'"
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov